.gitignore, README.md, package-lock.json, package.json, src/app.module.ts, src/main.ts, src/users.controller.ts
- updated readme to reflect our install/start more specifically
- added a .env workflow so that we can each have our own PG usernames and password
- updated port to 3001 so that we don't conflict with react's 3000
- add getById endpoint
=> use .env file, update readme, add getById

client/package-lock.json, client/package.json, client/public/index.html, client/src/App.js, client/src/Home.js, client/src/Login.js, client/src/Routes.js
Started on frontend work with basic routes
- Added basic dynamic routing with `<Routes> `component
- Added two dummy components for testing routes `<Home>` and `<Login>`
- Added Material-UI dependency for styling
=> Added react-route-dom with basic setup

client/package-lock.json, client/package.json, client/src/Login.js
- Added basic jsx for form text, fields, buttons, and links.
- Started styling component to match Figma wireframe.
- Placed control of form values in control of react state
=> Login Component

client/src/AboutUs.js, client/src/App.js, client/src/ContactUs.js, client/src/Header.js, client/src/HowItWorks.js, client/src/LibraryAndForum.js, client/src/Login.js, client/src/Routes.js, package-lock.json
- added ThemeProvider so we don't need to `useTheme` in every component
- add material ui `AppBar` component for header and react-router `Link`s to update url
- added empty components for each of the pages in the navbar
- added react-router `Route` handlers for ☝️ 
can someone add prettier or something 😢 this diff is ugly
1. `cd client && npm run start`
2. http://localhost:3000/contact_us
3. click navbar links
expect page content to change
=> NavBar actually navigates

client/package-lock.json, client/package.json, client/src/Assets.tsx, client/src/FilterGroup.tsx, client/src/Header.tsx, client/src/Home.tsx, client/src/NeedsAndOffers.tsx, client/src/Routes.tsx, client/src/types/index.ts
test criteria:
1. `cd client && npm run start`
2. http://localhost:3000/
3. in search bar, enter some text, hit magnifying glass button
4. see that you are taken to `/assets?search=<your_query>`
5. see that the page displays your query in the summary header
6. see that page displays your query in the search input
7. enter new search input and click magnifying glass
8. see URL search param and page update
9. open browser console 
10. play with the filters and see filters state in console is accurate
11. compare page styling to https://www.figma.com/file/fYkreARKdHsMh8iPSh7dti/Testing-File?node-id=0%3A1
=> assets page

client/src/AboutUs.tsx, client/src/DisplayGrids/BulletGrid.tsx, client/src/DisplayGrids/GridImages.tsx, client/src/DisplayGrids/InstructionGrid.tsx, client/src/DisplayGrids/index.ts, client/src/HowItWorks.tsx, client/src/QuestionList.tsx
This page has two versions depending on what tab is selected at the top. All of the content is created in variables so that the appropriate content can be displayed.
I've made a sub-component in the page for BulletGrid (the white squares section) and the InstructionGrid (text and images on the top half).
I made a component QuestionList for the clickable drop-down questions since I could see that being used in other places on the site.
=> Create How It Works page

client/src/Home.tsx, client/src/QuestionList.tsx
Updated QuestionList to use Accordion instead of List
Used QuestionList on Home and How It Works
=> Change QuestionList module to use Accordion

client/src/AboutUs.tsx, client/src/App.css, client/src/App.tsx, client/src/DisplayGrids/BulletGrid.tsx, client/src/DisplayGrids/GridImages.tsx, client/src/DisplayGrids/InstructionGrid.tsx, client/src/Header.tsx, client/src/Home.tsx, client/src/HowItWorks.tsx, client/src/Theme.tsx, client/src/TrustAndSafety.tsx, client/src/types/material-ui.d.ts
Created a Theme for the project! This allowed me to set a standard font and colors and move global styles out of components. This was fun, I look forward to playing more with it.
There are some pretty interesting changes coming in Material UI v5 (currently in alpha), including setting custom variants for existing components (https://next.material-ui.com/customization/theme-components/#adding-new-component-variants). The theme file will probably have to be re-written once we upgrade to v5.
I made some notes and posted them here about how to set up and use the Theme: https://www.notion.so/nstjean/Global-Theming-393d9a09037e45178740d89a03aafce4
=> Create custom theme

client/src/LibraryAndForum.tsx, client/src/Routes.tsx
Library and Forum component was deleted, as well as the route from Routes.tsx
=> removed library and forum component and route

client/package-lock.json, server/package-lock.json
make sure both services in app compile
1. `cd server && npm install && npm run start:dev`
2. `cd client && npm install && npm run start`
expect not to see errors in terminals where processes are running
expect http://localhost:3000/ to display homepage
=> audit fix dependencies in both apps

server/src/app.controller.spec.ts, server/src/users/entities/user.entity.ts
we've neglected our tests :(
but at least running them did catch one error that we made 💯 
i'm creating an issue to build out some of these tests
in the meantime:
run tests, and see they pass
`cd server && npm run test`
=> skip broken app test and fix a bad import that was breaking the others

.github/pull_request_template.md, CONTRIBUTING.md
everyone please read this doc!
if there is anything you can think of adding, go right ahead!
if my english isn't good ;) please fix it
=> add contributing and 'how we work' doc

server/src/app.controller.spec.ts, server/src/app.module.ts, server/src/organizations/dto/create-organization.dto.ts, server/src/organizations/dto/update-organization.dto.ts, server/src/organizations/entities/organization.entity.ts, server/src/organizations/organizations.controller.ts, server/src/organizations/organizations.module.ts, server/src/organizations/organizations.service.ts
DTOs to create and update
Organization Entity
Organizations Controller
Organizations Module
Organization Service
**1. Make http POST request to create new organization**
Postman post request: 
Proof that it exists in the database:
Code snippet for testing a POST request to ```http://localhost:3001/api/organizations``` 
```
{
"name": "Very Good Donators",
"description": "We donate things",
"website": "www.gooddonators.com",
"phone": "555-555-5555",
"city": "Newark",
"state": "New Jersey",
"ein": 123456789,
"tax_exempt_id": 987654321,
"address": "123 Olde Springs Rd"
}
```
Add a second organization:
```
{
"name": "ABC Volunteers",
"description": "We are volunteers",
"website": "www.abcvolunteers.com",
"phone": "555-666-7777",
"city": "Madison",
"state": "Wisconsin",
"ein": 999999999, …
```
=> Create organizations resource

README.md
just want this doc to get as much exposure as possible to new ppl
=> add contributing doc to readme

.github/pull_request_template.md
More detail on how to get Figma mocks link with specific node-id
N/A - just changing a comment with instructions in the PR template
=> update PR template mocks section

client/package-lock.json, client/src/Asset.tsx, client/src/SimpleSnackbar.tsx, client/src/assets/temp.ts, client/src/types/index.ts
[Mocks](link)
preReqs (to be checked by reviewer):
`cd client && npm run checks && cd ../server && npm run checks`
expect tests to pass
`cd client && npm run format && cd ../server && npm run format`
expect `git status` to show 0 files changed
repro steps:
expected: 
=> deleted  accidental extra code, now passes prettier errors

client/src/MessageInboxView.tsx, server/src/auth/auth.service.ts, server/src/messages/dto/create-message.dto.ts, server/src/messages/entities/message.entity.ts, server/src/messages/messages.controller.ts, server/src/users/entities/user.entity.ts, server/src/users/users.controller.ts
tinkered a bit and i think it should work with the messages<>users relationship
=> james' changes to messages BE<>FE hookup

CONTRIBUTING.md
markdown file update
no testing needed
please lmk if this new blurb makes sense
go through the suggested workflow to ensure it works
=> merge and conflict resolution links to contributing.md

client/src/features/action/assets/Asset.tsx, client/src/features/action/assets/Assets.tsx, client/src/features/home/NeedsAndOffers.tsx, client/src/types/index.ts, server/src/assets/entities/asset.entity.ts, server/test/stubs/assets.stub.ts
[Mocks](link)
Added two columns to asset entity: location and date posted. Location is null until Design decides how they'd like that to be posted (via user input or location feature). Date posted is formatted client-side with new Date().toLocaleDateString()
repro steps:
1. Use Postman to post an asset to backend/api/assets
2. Format raw JSON as I did below. I found out poster object needs a minimum of an id to be valid. JSON on the bottom is the response with the date posted added by the backend.
4. Navigate to client homepage (localhost:3000) 
5. Search for assets by title
6. Assets will appear with the date they were posted
expected: 
=> added location to assets BE & FE

client/src/features/Main.tsx, client/src/features/users/Auth/ForgotPassword.tsx, client/src/features/users/Auth/SetNewPassword.tsx, client/src/routes.tsx, server/src/assets/entities/asset.entity.ts
Created new component for password reset. In progress.
repro steps:
1. localhost:3000/set-new-password
2. See new component
=> FE: Password reset flow

client/src/features/users/Auth/SetNewPassword.tsx, client/src/features/users/Auth/SignupNonProfit.tsx, server/src/database/seeding/seed-data.ts, server/src/organizations/dto/create-organization.dto.ts, server/src/organizations/entities/organization.entity.ts, server/src/organizations/organizations.service.ts
FE wasn't compiling when i tried to run in `main`
FE request to create org (using string) would fail because BE was expecting number
repro steps:
1. in `client`, `npm run start`
2. build succeeds
3. in `server`, `npm run start:dev`
4. build succeeds
=> fix FE compile errors, align ein FE and BE typing, remove tax_exempt_id

server/package-lock.json, server/package.json, server/src/assets/assets.service.ts, server/src/categories/categories.service.ts, server/src/messages/messages.service.ts, server/src/organizations/organizations.service.ts, server/src/seeder/seeder.service.ts, server/src/transactions/transactions.service.ts, server/src/user-org/user-org.service.ts, server/src/users/users.service.ts, server/test/organizations/organizations.e2e-spec.ts, server/test/stubs/stub-factory.ts
Not related to a feature or issue. This PR is to update how we consume our updated packages' updated APIs.
Somewhere along the line, we upgraded Typeorm and NestJs,
=> New packages and required API changes

client/src/components/BannerSection.tsx, client/src/index.css, client/src/views/Home.tsx, server/package-lock.json
[Mocks -- Navigate to Home Option 1](https://www.figma.com/file/KE2Sw6ob07agN25RmeNuFg/GiveCycle-wireframes?node-id=4076%3A12228)
-  Implemented BannerSection using mui grid, so that it remains responsive across different screen widths.
- Mirrored styling of Figma mocks- included placeholder background image.
repro steps:
2. Go to home page
3. Scroll to banner section
- [mui grid docs](https://mui.com/material-ui/react-grid/)
=> Banner section

README.md, server/docs/RESOURCES.md
=> simplifying BE concepts

client/src/components/Header.tsx, client/src/components/Users/Auth/SetNewPassword.tsx, client/src/components/Users/Auth/SignUpUserAndNonprofit/http-sing-up-nonprofit.ts, client/src/views/Home.tsx, client/src/views/Inbox.tsx
use dynamic url for back-end api calls
repro steps:
expect the app to function as usual, no changes expected
n/a
=> use dynamic url from config

client/src/providers/UserProvider.tsx
Fixes double "/api/api" in authorization check 
repro steps:
2. login
3. navigate to homepage
expected: 
user should still be logged in
=> fix double api in auth path

client/package.json, client/src/components/Search.tsx, client/src/views/Home.tsx
- Relocate the search box at Home view [here](https://github.com/Nonprofit-Exchange-Hub/web-app/issues/223)
- Update devDependency of "@types/react" to "^18.0.9" for client
repro steps:
2. see if the search box has been relocated as in [Figma](https://www.figma.com/file/KE2Sw6ob07agN25RmeNuFg/GiveCycle-wireframes?node-id=6351%3A41839)
=> update Home view as requested in ticket 223

Dockerfile
[Mocks](link)
repro steps:
expected: 
=> use default npm version

.github/workflows/buil-image-or-fail.yml, client/src/views/SearchResults.tsx
[Mocks](link)
repro steps:
expected: 
=> fix the build

client/src/components/Users/Auth/ForgotPassword.tsx, client/src/components/Users/Auth/SetNewPassword.tsx, client/src/views/SignupCitizen.tsx
=> use new routes

.github/workflows/e2e.yml, server/package-lock.json, server/package.json, server/src/main.ts
we've got swagger docs now!!
repro steps:
1. http://localhost:3001/docs
test out the endpoints
- [nest docs](https://docs.nestjs.com/openapi/introduction)
=> swagger like mick jagger

client/src/components/Header.tsx, client/src/components/Users/UserAvatar.tsx, client/src/types/index.ts, server/src/acccount-manager/account-manager.controller.ts
Add a user avatar React component to render either the user's profile image or a default avatar. 
Adds profile_image_url to the returned data in the `session` method
repro steps:
1. localhost:3000
2. Either add an image url in the database to a user or use Postman to make a request like this:
```sh
curl --request PUT \
--url https://npc-fm7ocfzuva-uw.a.run.app/api/auth/users/profile/3 \
--header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
--header 'Cookie: NEH_is_cool=s%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoiQmlsbGllIiwibGFzdF9uYW1lIjoiRWlsaXNoIiwiZW1haWwiOiJ1c2VyMUZpcnN0QGV4YW1wbGUuY29tIiwiZW1haWxfbm90aWZpY2F0aW9uX29wdF9vdXQiOnRydWUsInByb2ZpbGVfaW1hZ2VfdXJsIjpudWxsLCJpYXQiOjE2NzcwMzY1NDEsImV4cCI6MTY3NzA0MDE0MX0.eLDKMJ-WvGqApJpBBT …
```
=> profile image

server/nest-cli.json, server/src/acccount-manager/account-manager.controller.ts, server/src/acccount-manager/dto/auth.dto.ts, server/src/acccount-manager/dto/create-user.dto.ts, server/src/acccount-manager/dto/create-user.internal.ts, server/src/acccount-manager/user.service.ts, server/src/assets/assets.controller.ts, server/src/categories/categories.controller.ts, server/src/database/seeding/seed-data.ts, server/src/main.ts, server/src/messages/messages.controller.ts, server/src/organizations/organizations.controller.ts, server/src/transactions/transactions.controller.ts, server/src/user-org/user-org.controller.ts, server/test/account-manager/account-manager.controller.e2e-spec.ts, server/test/assets/assets.e2e-spec.ts, server/test/stubs/stub-factory.ts, server/test/stubs/users.stub.ts
Building on the work that @jd2rogers2 did to add swagger to the server, I am adding the rest of the decorators to document all the endpoints in the `account` module
repro steps:
1. localhost:3001/docs 
2. Expect to see the expected body for each request in the auth section
3. You can use the swagger ui to interact with the backend
Only the account endpoints have been fully documented.
https://docs.nestjs.com/openapi/introduction
=> 297 document account endpoint

client/src/routes/routes.ts, client/src/views/User.tsx
Just cleaning up the profile route
repro steps:
2. start ui and login with a valid user credential
expected: 
- when you click on the `My Profile` link, the route reads `/profile` instead of `/users/:userId`
n/a
=> fix profile route

README.md
This is a small PR updating the main `README.md` to use `npm i` instead of `npm ci` for installing dependencies.  This change was suggested by @esteban-gs. 
- None applicable as this change is in the `README.md`
- None applicable
=> update readme: remove np ci in favor of npm i

.github/workflows/buil-image-or-fail.yml, .github/workflows/lint.yml
Adding linting as a check to our CI pipeline
repro steps:
1. Open a repo, push a commit and watch the tests run. Lint failures should block merging.
=> linting github actions check

client/src/components/Users/Auth/SignUpCitizen/SignUpCitizen.tsx, client/src/components/Users/Auth/SignUpCitizen/UserSignupData.ts, client/src/components/Users/Auth/SignUpCitizen/interests.ts, server/src/acccount-manager/account-manager.controller.ts, server/src/database/seeding/seed-data.ts
-Made bio, zip code, and interests inputs functional and included data in post request
-Fixed a bug that was happening with the city/state select inputs 
-Post request to create user works (successfully creates user) but still throws an error for some reason
-Profile_image_url is not included in post request, currently image input is a file upload and not a text field for a url. This will probably require some more steps in order to store file as url
-Added interests from frontend to category seeds in backend, so that these interests can be saved 
-Commented out email_verified check when logging in, to allow us to work around that for now
=> Match back and front end user signup

server/sample.env, server/src/acccount-manager/account-manager.controller.ts, server/src/database-connection.service.ts, server/src/file-storage/file-storage.service.ts
This PR adds better management of our app env vars. I added an extra env var to toggle logging on and off and added extensibility for `development` and `staging` environments. 
I added a app configs validation step that provides some useful info.
This will require changing some configs in our staging environments and changing devs' local `.env` files.
repro steps:
1. start the express server
2. expect the app to work
3. If you set an invalid value for `NODE_ENV`, expect to see some helpful error messages
=> 135 server env configs

client/src/components/DisplayGrids/BulletGrid.tsx, client/src/components/DisplayGrids/GridImages.tsx, client/src/components/DisplayGrids/InstructionGrid.tsx, client/src/views/AboutUs.tsx, client/src/views/User.tsx
This PR has fixes for warnings regarding the need of keys when using `.map()`.  This should help reduce the noise in our browser console.
There aren't any functional changes with the PR.  That said, we can still go through the app for manual testing.
=> minor fixes - add keys to maps

client/src/index.tsx
@esteban-gs Hey Esteban, this was my ticket: https://github.com/orgs/Nonprofit-Exchange-Hub/projects/14/views/1?pane=issue&itemId=31704146
I think this pull request fulfills the ticket.
=> Updated client/index.tsx to React 18 root render method

client/package-lock.json, client/src/components/Users/Auth/SignUpCitizen/validation-rules.ts, client/src/components/Users/Auth/SignUpUserAndNonprofit/SignUpUserAndNonprofit.tsx, client/src/types/index.ts, client/src/views/User.tsx, server/src/database-connection.service.ts
-Show interests, bio, city/state/zip, and profile image on profile
-add 'Edit Profile' button
=> Fix profile page

client/src/components/Users/Auth/SignUpCitizen/StepTwo.tsx
This PR adds code to show errors for the `select` component.
repro steps:
1. fill out the user sign up form
2. On the location step, leave state blank
3. Expect a `required` error message to show
=> Show select field error

server/src/acccount-manager/account-manager.controller.ts
This PR makes the email verification requirement only enabled in `staging`
repro steps:
1. In local development, signup email verification is not triggered
2. In staging, it is triggered
=> Environments behavior

server/src/acccount-manager/account-manager.controller.ts
[Mocks](link)
repro steps:
expected: 
=> Only send reset password email in staging

server/sample.env, server/src/acccount-manager/account-manager.controller.ts
[Mocks](link)
repro steps:
expected: 
=> get cookie domain from env var

client/package-lock.json, client/package.json, client/src/components/Header.tsx, client/src/routes/routes.ts, client/src/views/Main.tsx, client/src/views/MakePost.tsx
Hi Team,
Please review the changes. As mentioned, the 'Make a Post' functionality is implemented as per the Figma designs.
Let me know if any changes need to be made.
=> Make a post functionlity is added.
